.TH "ADIS16470Body" 3 "Mon Feb 7 2022" "SupersonicTestRocket Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADIS16470Body
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBgyros\fP [3] = {0}"
.br
.ti -1c
.RI "float \fBacc\fP [3] = {0}"
.br
.ti -1c
.RI "float \fBtemp\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SupersonicTestRocket Logger from the source code\&.
