.TH "ADIS16470Packet" 3 "Mon Feb 7 2022" "SupersonicTestRocket Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADIS16470Packet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPacket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBADIS16470Packet\fP (\fBPacketHeader\fP h)"
.br
.ti -1c
.RI "float \fBgetGyro\fP (size_t i)"
.br
.ti -1c
.RI "void \fBgetGyros\fP (float g[3])"
.br
.ti -1c
.RI "float \fBgetXGyro\fP ()"
.br
.ti -1c
.RI "float \fBgetYGyro\fP ()"
.br
.ti -1c
.RI "float \fBgetZGyro\fP ()"
.br
.ti -1c
.RI "float \fBgetAcc\fP (size_t i)"
.br
.ti -1c
.RI "void \fBgetAccs\fP (float a[3])"
.br
.ti -1c
.RI "float \fBgetXAcc\fP ()"
.br
.ti -1c
.RI "float \fBgetYAcc\fP ()"
.br
.ti -1c
.RI "float \fBgetZAcc\fP ()"
.br
.ti -1c
.RI "float \fBgetTemp\fP ()"
.br
.ti -1c
.RI "void \fBsetGyro\fP (size_t i, float g)"
.br
.ti -1c
.RI "void \fBsetGyros\fP (const float g[3])"
.br
.ti -1c
.RI "void \fBsetXGyro\fP (float g)"
.br
.ti -1c
.RI "void \fBsetYGyro\fP (float g)"
.br
.ti -1c
.RI "void \fBsetZGyro\fP (float g)"
.br
.ti -1c
.RI "void \fBsetAcc\fP (size_t i, float a)"
.br
.ti -1c
.RI "void \fBsetAccs\fP (const float a[3])"
.br
.ti -1c
.RI "void \fBsetXAcc\fP (float a)"
.br
.ti -1c
.RI "void \fBsetYAcc\fP (float a)"
.br
.ti -1c
.RI "void \fBsetZAcc\fP (float a)"
.br
.ti -1c
.RI "void \fBsetTemp\fP (float t)"
.br
.ti -1c
.RI "void \fBsetContent\fP (\fBADIS16470Body\fP b)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SupersonicTestRocket Logger from the source code\&.
