.TH "AISx120SXPacket" 3 "Mon Feb 7 2022" "SupersonicTestRocket Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AISx120SXPacket
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPacket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAISx120SXPacket\fP (\fBPacketHeader\fP h)"
.br
.ti -1c
.RI "float \fBgetXaccel\fP ()"
.br
.ti -1c
.RI "float \fBgetYaccel\fP ()"
.br
.ti -1c
.RI "void \fBgetAccel\fP (float a[2])"
.br
.ti -1c
.RI "void \fBsetAcceleration\fP (const float a[2])"
.br
.ti -1c
.RI "void \fBsetXaccel\fP (float a_x)"
.br
.ti -1c
.RI "void \fBsetYaccel\fP (float a_y)"
.br
.ti -1c
.RI "void \fBsetContent\fP (\fBAISx120SXBody\fP b)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SupersonicTestRocket Logger from the source code\&.
