.TH "AISx120SXBody" 3 "Mon Feb 7 2022" "SupersonicTestRocket Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AISx120SXBody
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBaccel\fP [2] = {0}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SupersonicTestRocket Logger from the source code\&.
