.TH "HoneywellRscWrapper" 3 "Mon Feb 7 2022" "SupersonicTestRocket Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HoneywellRscWrapper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHoneywellRscWrapper\fP (int DR, int CS_EE, int CS_ADC, int SPI_BUS, RSC_DATA_RATE data_r, uint32_t desired_P)"
.br
.ti -1c
.RI "bool \fBsetup\fP (uint32_t attempts, uint32_t delayDuration)"
.br
.ti -1c
.RI "const char * \fBmyName\fP ()"
.br
.ti -1c
.RI "uint8_t \fBgetSensorQty\fP ()"
.br
.ti -1c
.RI "bool \fBisDue\fP (uint32_t currMicros, volatile bool &triggeredDR)"
.br
.ti -1c
.RI "bool \fBisMeasurementInvalid\fP ()"
.br
.ti -1c
.RI "READING_T \fBcurrReadType\fP ()"
.br
.ti -1c
.RI "READING_T \fBnextReadType\fP ()"
.br
.ti -1c
.RI "\fBHoneywellRSCPacket\fP * \fBgetPacket\fP (uint32_t currMicros)"
.br
.ti -1c
.RI "\fBHoneywellRSCPacket\fP * \fBgetSerialPackets\fP (uint32_t currMicros)"
.br
.ti -1c
.RI "\fBPacketHeader\fP \fBgetHeader\fP (uint32_t currMicros)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBPacketHeader\fP HoneywellRscWrapper::getHeader (uint32_t currMicros)\fC [virtual]\fP"

.PP
Implements \fBSensor\fP\&.
.SS "\fBHoneywellRSCPacket\fP * HoneywellRscWrapper::getPacket (uint32_t currMicros)\fC [virtual]\fP"

.PP
Implements \fBSensor\fP\&.
.SS "bool HoneywellRscWrapper::isDue (uint32_t currMicros, volatile bool & triggeredDR)\fC [virtual]\fP"

.PP
Implements \fBSensor\fP\&.
.SS "bool HoneywellRscWrapper::isMeasurementInvalid ()\fC [virtual]\fP"

.PP
Reimplemented from \fBSensor\fP\&.
.SS "const char * HoneywellRscWrapper::myName ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSensor\fP\&.
.SS "bool HoneywellRscWrapper::setup (uint32_t attempts, uint32_t delayDuration)\fC [virtual]\fP"

.PP
Implements \fBSensor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SupersonicTestRocket Logger from the source code\&.
