.TH "PacketHeader" 3 "Mon Feb 7 2022" "SupersonicTestRocket Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PacketHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "packetType \fBpacketType_\fP = NO_PACKET"
.br
.ti -1c
.RI "uint8_t \fBpacketSize\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBsensorID\fP = 0"
.br
.ti -1c
.RI "uint8_t \fBerrorCode\fP = 0xff"
.br
.ti -1c
.RI "uint32_t \fBtimestamp\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SupersonicTestRocket Logger from the source code\&.
