.TH "PushButtonArrayEvent" 3 "Mon Feb 7 2022" "SupersonicTestRocket Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PushButtonArrayEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBactivatedStatus\fP ()"
.br
.ti -1c
.RI "void \fBactivateEvent\fP ()"
.br
.ti -1c
.RI "void \fBdeactivateEvent\fP ()"
.br
.ti -1c
.RI "void \fBcreateEvent\fP (uint8_t state, uint8_t nextState, uint32_t windowStart, uint32_t windowEnd)"
.br
.ti -1c
.RI "void \fBdeleteEvent\fP ()"
.br
.ti -1c
.RI "bool \fBdeletedStatus\fP ()"
.br
.ti -1c
.RI "eventType \fBcheckEvent\fP (uint8_t lastState, uint8_t state, uint32_t stateDuration)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SupersonicTestRocket Logger from the source code\&.
