.TH "Sensor" 3 "Mon Feb 7 2022" "SupersonicTestRocket Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensor
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBADIS16470Wrapper\fP, \fBAISx120SXWrapper\fP, \fBHoneywellRscWrapper\fP, and \fBMAX31855Wrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSensor\fP (uint8_t sensorID)"
.br
.ti -1c
.RI "void \fBsetupProperties\fP (uint32_t checkInterval_, uint32_t checkIntervalMargin_, uint32_t measInterval_, bool DR_driven_)"
.br
.ti -1c
.RI "virtual bool \fBsetup\fP (uint32_t attempts, uint32_t delayDuration)=0"
.br
.ti -1c
.RI "virtual const char * \fBmyName\fP ()=0"
.br
.ti -1c
.RI "bool \fBisDueByTime\fP (uint32_t currMicros)"
.br
.ti -1c
.RI "bool \fBisDueByDR\fP (uint32_t currMicros, volatile bool &triggeredDR)"
.br
.ti -1c
.RI "virtual bool \fBisDue\fP (uint32_t currMicros, volatile bool &triggeredDR)=0"
.br
.ti -1c
.RI "bool \fBisMeasurementLate\fP (uint32_t currMicros)"
.br
.ti -1c
.RI "virtual bool \fBisMeasurementInvalid\fP ()"
.br
.ti -1c
.RI "bool * \fBgetErrors\fP ()"
.br
.ti -1c
.RI "uint8_t \fBgetErrorCode\fP (uint32_t currMicros)"
.br
.ti -1c
.RI "bool * \fBdecodeErrorCode\fP (uint8_t errorCode)"
.br
.ti -1c
.RI "\fBPacketHeader\fP \fBgetHeader\fP (packetType packetType_, uint8_t packetSize_, uint32_t currMicros)"
.br
.ti -1c
.RI "virtual \fBPacketHeader\fP \fBgetHeader\fP (uint32_t currMicros)=0"
.br
.ti -1c
.RI "float \fBgenerateFakeData\fP (float minValue, float maxValue, uint32_t currMicros, float offset=0, uint32_t period=5000000)"
.br
.ti -1c
.RI "virtual \fBPacket\fP * \fBgetPacket\fP (uint32_t currMicros)=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBactive\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const uint8_t \fBSENSOR_ID\fP"
.br
.ti -1c
.RI "bool \fBchecksumError\fP"
.br
.ti -1c
.RI "uint32_t \fBprevMeasTime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SupersonicTestRocket Logger from the source code\&.
